name: Feature Request
description: Propose an enhancement
title: "[feat] "
labels:
  - enhancement
  - P2
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user/business problem are we solving?
      placeholder: Explain pain point and impact
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe desired behavior and scope
      placeholder: What should be built?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Scenario A works
        - [ ] Scenario B works
        - [ ] No regression in ...
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
        - P3
    validations:
      required: true
